apiVersion: apps/v1
kind: Deployment
metadata:
  name: companion-obc
  namespace: engineering-prod
  labels:
    app: companion
spec:
  replicas: 1
  selector:
    matchLabels:
      app: companion
  template:
    metadata:
      labels:
        app: companion
    spec:
      containers:
      - name: companion-container
        image: ghcr.io/bitfocus/companion/companion:3.3.1-7001-stable-ee7c3daa
        ports:
        - containerPort: 8000
        - containerPort: 16622
        - containerPort: 28492
        resources:
          requests:
            cpu: 500m
            memory: 512m
          limits:
            cpu: 1000m
            memory: 1024Mi
        volumeMounts:
        - mountPath: /companion
          name: companion-volume
      restartPolicy: Always
      volumes:
        - name: companion-volume
          persistentVolumeClaim:
            claimName: mr2-nas-companion-pvc
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: companion-gw
  namespace: engineering-prod
spec:
  selector:
    istio: ingressgateway
  servers:
    - hosts:
        - companion.vpc3.mnw.no
      port:
        name: http
        number: 80
        protocol: HTTP
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: companion-vs
  namespace: engineering-prod
spec:
  gateways:
    - companion-gw
  hosts:
    - companion.vpc3.mnw.no
  http:
    - name: companion-obc
      route:
        - destination:
            host: companion-svc
            port:
              number: 80
---
apiVersion: v1
kind: Service
metadata:
  name: companion-svc
  namespace: engineering-prod
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8000
  selector:
    app: companion
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: companion-nodeport
spec:
  type: NodePort
  selector:
    app: companion
  ports:
    - port: 16622
      targetPort: 16622
      protocol: TCP
      nodePort: 32622
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mr2-nas-companion-pvc
  namespace: engineering-prod
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: companion-sc
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mr2-nas-companion-pv
  namespace: engineering-prod
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: companion-sc
  mountOptions:
    - hard
    - nfsvers=4
  nfs:
    path: /volume1/k8sdata/companion
    server: 10.1.138.199